### PR TITLE
LSRD-679: Allow ordering V006 modis products

### PR DESCRIPTION
**Pull request by jakebrinkmann**
* Allows regex to validate both 005 or 006 in filename inputs

capture

### CODE REVIEW

**Comment by caustin-usgs** [comment]
could you update sensor_acqids https://github.com/USGS-EROS/espa-api/blob/master/test/version0_testorders.py#L97
to include a collection 6 key ?

**Comment by jakebrinkmann** [comment]
Yea, should I also do the same in test_api?

https://github.com/USGS-EROS/espa-api/blob/master/test/test_api.py#L165
```python

    def test_modis_resize(self):
        """
        Most common issue of orders resizing MODIS to 30m pixels, without setting the extents
        """
        modis_order = {'mod09a1': {'inputs': 'mod09a1.a2000072.h02v09.005.2008237032813',
                                   'products': ['l1']},
                       'resampling_method': 'cc',
                       'resize': {'pixel_size': 30,
                                  'pixel_size_units': 'meters'},
                       'format': 'gtiff'}

```

https://github.com/USGS-EROS/espa-api/blob/master/test/test_api.py#L229
```python
class TestInventory(unittest.TestCase):
    def setUp(self):
        os.environ['espa_api_testing'] = 'True'
        self.lta_prod_good = u'LT50300372011275PAC01'
        self.lta_prod_bad = u'LE70290302001200EDC01'
        self.lpdaac_prod_good = u'MOD09A1.A2001209.h10v04.005.2007042201314'
        self.lpdaac_prod_bad = u'MOD09A1.A2001209.h10v04.005.2007042201315'

```

**Comment by caustin-usgs** [comment]
those regex mods really just need to get exercised by one test. given the deprecation of collection 5 in the future, we could probably just flip the test_api references to 006

**Comment by jakebrinkmann** [comment]
[This logic](https://github.com/USGS-EROS/espa-api/blob/master/test/version0_testorders.py#L110) only allows 1 modis product to be returned from [testorders.build_base_order()](https://github.com/USGS-EROS/espa-api/blob/master/test/test_api.py#L121)

I'll update that lpdaac_prod_good to a valid 006 scene id

**Comment by caustin-usgs** [comment]
it'd work if you divided up the sensor types (mod09a1, etc) between the two collection ids.

**Comment by jakebrinkmann** [comment]
OK, MODIS section returned from `testorders.build_base_order()` would now be inter-mixed 005/006 products: 

```python
'mod09a1': {'inputs': ['MOD09A1.A2000072.h02v09.005.2008237032813'],
  'products': ['l1', 'stats']},
 'mod09ga': {'inputs': ['MOD09GA.A2016305.h11v04.006.2016314200836'],
  'products': ['l1', 'stats']},
 'mod09gq': {'inputs': ['MOD09GQ.A2016305.h11v04.006.2016314200836'],
  'products': ['l1', 'stats']},
 'mod09q1': {'inputs': ['MOD09Q1.A2000072.h02v09.005.2008237032813'],
  'products': ['l1', 'stats']},
 'myd13a1': {'inputs': ['MYD13A1.A2000072.h02v09.005.2008237032813'],
  'products': ['l1', 'stats']},
 'myd13a2': {'inputs': ['MYD13A2.A2016305.h11v04.006.2016314200836'],
  'products': ['l1', 'stats']},
 'myd13a3': {'inputs': ['MYD13A3.A2016305.h11v04.006.2016314200836'],
  'products': ['l1', 'stats']},
 'myd13q1': {'inputs': ['MYD13Q1.A2000072.h02v09.005.2008237032813'],
  'products': ['l1', 'stats']}
```

unittest test.test_api passed

**Pull request merged**
