### PR TITLE
Version0 development cgaustin

### PR DESCRIPTION
**Pull request by caustin-usgs**
This is what I've initially come up with as a solution for testing some of the SQL heavy production api methods. I'm not sure how else to sufficiently test those methods without hitting a database.

the setUp method in test_production_apiv0 sets an environment var, thats picked up by api_cfg, and looks for a .cfgnfo-test file in order to connect to  a test DB instance. The MockOrder class is then responsible for adding and removing test instances from the db.

@davidvhill @klsmith-usgs

### CODE REVIEW

**Comment by klsmith-usgs** [comment]
This makes sense to me. Write a bunch of dummy values, perform operations
with those values, then remove dummy values. This could even be tied into
testing for placing an order, and route the dummy values through that.

Would going so far as to create a new mock table, or something similar, to
prevent possible interaction with real data be a good idea? I ask because
isn't the test system actually used to do some processing? Even if not, it
might be a good fail-safe measure anyways.

On Tue, Mar 1, 2016 at 9:42 AM, Clay Austin <notifications@github.com>
wrote:

> This is what I've initially come up with as a solution for testing some of
> the SQL heavy production api methods. I'm not sure how else to sufficiently
> test those methods without hitting a database.
>
> the setUp method in test_production_apiv0 sets an environment var, thats
> picked up by api_cfg, and looks for a .cfgnfo-test file in order to connect
> to a test DB instance. The MockOrder class is then responsible for adding
> and removing test instances from the db.
>
> @davidvhill <https://github.com/davidvhill> @klsmith-usgs
> <https://github.com/klsmith-usgs>
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/USGS-EROS/espa-api/pull/8
> Commit Summary
>
>    - initial thoughts at setup for testing production api functions
>    - fix mock order
>
> File Changes
>
>    - *A* api/domain/mock_order.py
>    <https://github.com/USGS-EROS/espa-api/pull/8/files#diff-0> (42)
>    - *M* api/utils.py
>    <https://github.com/USGS-EROS/espa-api/pull/8/files#diff-1> (9)
>    - *A* test/test_production_apiv0.py
>    <https://github.com/USGS-EROS/espa-api/pull/8/files#diff-2> (75)
>
> Patch Links:
>
>    - https://github.com/USGS-EROS/espa-api/pull/8.patch
>    - https://github.com/USGS-EROS/espa-api/pull/8.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/USGS-EROS/espa-api/pull/8>.
>



-- 
Kelcy Smith
Software Engineer
Stinger Ghaffarian Technologies (SGT, Inc.)
Contractor to the U.S. Geological Survey (USGS)
Earth Resources Observation and Science (EROS) Center
47914 252nd St
Sioux Falls, South Dakota 57198
Office: (605) 594-2836
Fax: (605) 594-6529
Email: klsmith@usgs.gov

**Comment by caustin-usgs** [comment]
I'd rather not muck with maintaining structure in multiple tables. the whole point behind the test database is being able to ruin it, and bring it back w/o consequence.

do you think it'd be possible to pull dummy orders from what you wrote for validation testing?

**Comment by davidvhill** [comment]
looking...

**Comment by davidvhill** [comment]
without having gotten through all the code, the initial thought would be to create a whole new test schema (in whatever database you are currently connected to), populate it with the necessary bootstrap data, do whatever you want against it (including ruining it), then when the tests are done wipe it out.

**Pull request merged**
