### PR TITLE
move dbconnect emails errors lpdaac lta nlaps user utils others into …

### PR DESCRIPTION
**Pull request by caustin-usgs**
this commit moves a few modules into the domain dir, and updates pointers to the moved modules
@klsmith-usgs

### CODE REVIEW

**Comment by davidvhill** [comment]
Those really aren't domain objects.

**Comment by klsmith-usgs** [comment]
What are we defining as a 'domain' level object?

On Thu, Mar 3, 2016 at 8:13 AM, David V. Hill <notifications@github.com>
wrote:

> Those really aren't domain objects.
> On Mar 3, 2016 8:09 AM, "Clay Austin" <notifications@github.com> wrote:
>
> > this commit moves a few modules into the domain dir, and updates pointers
> > to the moved modules
> > @klsmith-usgs <https://github.com/klsmith-usgs>
> > ------------------------------
> > You can view, comment on, or merge this pull request online at:
> >
> > https://github.com/USGS-EROS/espa-api/pull/9
> > Commit Summary
> >
> > - move dbconnect emails errors lpdaac lta nlaps user utils others into
> > domain dir
> >
> > File Changes
> >
> > - *M* api/api_logging.py
> > <https://github.com/USGS-EROS/espa-api/pull/9/files#diff-0> (2)
> > - *M* api/domain/config.py
> > <https://github.com/USGS-EROS/espa-api/pull/9/files#diff-1> (4)
> > - *R* api/domain/dbconnect.py
> > <https://github.com/USGS-EROS/espa-api/pull/9/files#diff-2> (0)
> > - *R* api/domain/emails.py
> > <https://github.com/USGS-EROS/espa-api/pull/9/files#diff-3> (0)
> > - *R* api/domain/errors.py
> > <https://github.com/USGS-EROS/espa-api/pull/9/files#diff-4> (0)
> > - *R* api/domain/lpdaac.py
> > <https://github.com/USGS-EROS/espa-api/pull/9/files#diff-5> (2)
> > - *R* api/domain/lta.py
> > <https://github.com/USGS-EROS/espa-api/pull/9/files#diff-6> (0)
> > - *M* api/domain/mock_order.py
> > <https://github.com/USGS-EROS/espa-api/pull/9/files#diff-7> (4)
> > - *R* api/domain/nlaps.py
> > <https://github.com/USGS-EROS/espa-api/pull/9/files#diff-8> (0)
> > - *R* api/domain/onlinecache.py
> > <https://github.com/USGS-EROS/espa-api/pull/9/files#diff-9> (2)
> > - *M* api/domain/order.py
> > <https://github.com/USGS-EROS/espa-api/pull/9/files#diff-10> (4)
> > - *M* api/domain/scene.py
> > <https://github.com/USGS-EROS/espa-api/pull/9/files#diff-11> (4)
> > - *M* api/domain/sensor.py
> > <https://github.com/USGS-EROS/espa-api/pull/9/files#diff-12> (5)
> > - *R* api/domain/sshcmd.py
> > <https://github.com/USGS-EROS/espa-api/pull/9/files#diff-13> (0)
> > - *R* api/domain/user.py
> > <https://github.com/USGS-EROS/espa-api/pull/9/files#diff-14> (6)
> > - *R* api/domain/utils.py
> > <https://github.com/USGS-EROS/espa-api/pull/9/files#diff-15> (2)
> > - *M* api/providers/ordering/ordering_provider.py
> > <https://github.com/USGS-EROS/espa-api/pull/9/files#diff-16> (10)
> > - *M* api/providers/ordering/production_provider.py
> > <https://github.com/USGS-EROS/espa-api/pull/9/files#diff-17> (16)
> > - *M* test/test_apiv0.py
> > <https://github.com/USGS-EROS/espa-api/pull/9/files#diff-18> (4)
> > - *A* test/test_flask_production_transportv0.py
> > <https://github.com/USGS-EROS/espa-api/pull/9/files#diff-19> (77)
> > - *M* test/test_flask_transportv0.py
> > <https://github.com/USGS-EROS/espa-api/pull/9/files#diff-20> (4)
> > - *M* test/test_production_apiv0.py
> > <https://github.com/USGS-EROS/espa-api/pull/9/files#diff-21> (4)
> > - *M* transport.py
> > <https://github.com/USGS-EROS/espa-api/pull/9/files#diff-22> (4)
> >
> > Patch Links:
> >
> > - https://github.com/USGS-EROS/espa-api/pull/9.patch
> > - https://github.com/USGS-EROS/espa-api/pull/9.diff
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/USGS-EROS/espa-api/pull/9>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/USGS-EROS/espa-api/pull/9#issuecomment-191779103>.
>



-- 
Kelcy Smith
Software Engineer
Stinger Ghaffarian Technologies (SGT, Inc.)
Contractor to the U.S. Geological Survey (USGS)
Earth Resources Observation and Science (EROS) Center
47914 252nd St
Sioux Falls, South Dakota 57198
Office: (605) 594-2836
Fax: (605) 594-6529
Email: klsmith@usgs.gov

**Comment by caustin-usgs** [comment]
I considered it the space for our business specific logic/code

**Comment by davidvhill** [comment]
Orders, products, users, sensors etc.  The major nouns of the system and
the ability to describe them

**Comment by klsmith-usgs** [comment]
So, not utils.py, dbconnect.py, sshcmd.py, email.py, etc..? Some of the
other ones somewhat fit that description, so I'm confused on where the line
is. My concern is that if we are going to be fussy about this and
potentially other locations, then we need to have a good, narrow definition.

On Thu, Mar 3, 2016 at 8:19 AM, David V. Hill <notifications@github.com>
wrote:

> Orders, products, users, sensors etc. The major nouns of the system and
> the ability to describe them
> On Mar 3, 2016 8:15 AM, "Kelcy Smith" <notifications@github.com> wrote:
>
> > What are we defining as a 'domain' level object?
> >
> > On Thu, Mar 3, 2016 at 8:13 AM, David V. Hill <notifications@github.com>
> > wrote:
> >
> > > Those really aren't domain objects.
> > > On Mar 3, 2016 8:09 AM, "Clay Austin" <notifications@github.com>
> wrote:
> > >
> > > > this commit moves a few modules into the domain dir, and updates
> > pointers
> > > > to the moved modules
> > > > @klsmith-usgs <https://github.com/klsmith-usgs>
> > > > ------------------------------
> > > > You can view, comment on, or merge this pull request online at:
> > > >
> > > > https://github.com/USGS-EROS/espa-api/pull/9
> > > > Commit Summary
> > > >
> > > > - move dbconnect emails errors lpdaac lta nlaps user utils others
> into
> > > > domain dir
> > > >
> > > > File Changes
> > > >
>
> > > > - *M* api/api_logging.py
> > > > <https://github.com/USGS-EROS/espa-api/pull/9/files#diff-0> (2)
> > > > - *M* api/domain/config.py
> > > > <https://github.com/USGS-EROS/espa-api/pull/9/files#diff-1> (4)
> > > > - *R* api/domain/dbconnect.py
> > > > <https://github.com/USGS-EROS/espa-api/pull/9/files#diff-2> (0)
> > > > - *R* api/domain/emails.py
> > > > <https://github.com/USGS-EROS/espa-api/pull/9/files#diff-3> (0)
> > > > - *R* api/domain/errors.py
> > > > <https://github.com/USGS-EROS/espa-api/pull/9/files#diff-4> (0)
> > > > - *R* api/domain/lpdaac.py
> > > > <https://github.com/USGS-EROS/espa-api/pull/9/files#diff-5> (2)
> > > > - *R* api/domain/lta.py
> > > > <https://github.com/USGS-EROS/espa-api/pull/9/files#diff-6> (0)
> > > > - *M* api/domain/mock_order.py
> > > > <https://github.com/USGS-EROS/espa-api/pull/9/files#diff-7> (4)
> > > > - *R* api/domain/nlaps.py
> > > > <https://github.com/USGS-EROS/espa-api/pull/9/files#diff-8> (0)
> > > > - *R* api/domain/onlinecache.py
> > > > <https://github.com/USGS-EROS/espa-api/pull/9/files#diff-9> (2)
> > > > - *M* api/domain/order.py
> > > > <https://github.com/USGS-EROS/espa-api/pull/9/files#diff-10> (4)
> > > > - *M* api/domain/scene.py
> > > > <https://github.com/USGS-EROS/espa-api/pull/9/files#diff-11> (4)
> > > > - *M* api/domain/sensor.py
> > > > <https://github.com/USGS-EROS/espa-api/pull/9/files#diff-12> (5)
> > > > - *R* api/domain/sshcmd.py
> > > > <https://github.com/USGS-EROS/espa-api/pull/9/files#diff-13> (0)
> > > > - *R* api/domain/user.py
> > > > <https://github.com/USGS-EROS/espa-api/pull/9/files#diff-14> (6)
> > > > - *R* api/domain/utils.py
> > > > <https://github.com/USGS-EROS/espa-api/pull/9/files#diff-15> (2)
> > > > - *M* api/providers/ordering/ordering_provider.py
> > > > <https://github.com/USGS-EROS/espa-api/pull/9/files#diff-16> (10)
> > > > - *M* api/providers/ordering/production_provider.py
> > > > <https://github.com/USGS-EROS/espa-api/pull/9/files#diff-17> (16)
> > > > - *M* test/test_apiv0.py
> > > > <https://github.com/USGS-EROS/espa-api/pull/9/files#diff-18> (4)
> > > > - *A* test/test_flask_production_transportv0.py
> > > > <https://github.com/USGS-EROS/espa-api/pull/9/files#diff-19> (77)
> > > > - *M* test/test_flask_transportv0.py
> > > > <https://github.com/USGS-EROS/espa-api/pull/9/files#diff-20> (4)
> > > > - *M* test/test_production_apiv0.py
> > > > <https://github.com/USGS-EROS/espa-api/pull/9/files#diff-21> (4)
> > > > - *M* transport.py
> > > > <https://github.com/USGS-EROS/espa-api/pull/9/files#diff-22> (4)
> > > >
> > > > Patch Links:
> > > >
> > > > - https://github.com/USGS-EROS/espa-api/pull/9.patch
> > > > - https://github.com/USGS-EROS/espa-api/pull/9.diff
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <https://github.com/USGS-EROS/espa-api/pull/9>.
> > >
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/USGS-EROS/espa-api/pull/9#issuecomment-191779103>.
> > >
> >
> >
> >
> > --
> > Kelcy Smith
> > Software Engineer
> > Stinger Ghaffarian Technologies (SGT, Inc.)
> > Contractor to the U.S. Geological Survey (USGS)
> > Earth Resources Observation and Science (EROS) Center
> > 47914 252nd St
> > Sioux Falls, South Dakota 57198
> > Office: (605) 594-2836
> > Fax: (605) 594-6529
> > Email: klsmith@usgs.gov
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/USGS-EROS/espa-api/pull/9#issuecomment-191780124>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/USGS-EROS/espa-api/pull/9#issuecomment-191781458>.
>



-- 
Kelcy Smith
Software Engineer
Stinger Ghaffarian Technologies (SGT, Inc.)
Contractor to the U.S. Geological Survey (USGS)
Earth Resources Observation and Science (EROS) Center
47914 252nd St
Sioux Falls, South Dakota 57198
Office: (605) 594-2836
Fax: (605) 594-6529
Email: klsmith@usgs.gov

**Comment by caustin-usgs** [comment]
the primary goal of this commit was cleaning up the organization of the modules. most of these were just living under api/  and that didn't feel right to me. an argument could be made to create an api/utils dir, and keep dbconnect, sshcmd, etc there.    I dont think there are much, if any, more new modules to create. So if keeping this commit as is, is confusing, i can certainly reorg things again.

**Comment by davidvhill** [comment]
I'll be there in just a bit and will help the understanding ;-)
On Mar 3, 2016 8:34 AM, "Kelcy Smith" <notifications@github.com> wrote:

So, not utils.py, dbconnect.py, sshcmd.py, email.py, etc..? Some of the
other ones somewhat fit that description, so I'm confused on where the line
is. My concern is that if we are going to be fussy about this and
potentially other locations, then we need to have a good, narrow definition.

On Thu, Mar 3, 2016 at 8:19 AM, David V. Hill <notifications@github.com>

wrote:

> Orders, products, users, sensors etc. The major nouns of the system and
> the ability to describe them
> On Mar 3, 2016 8:15 AM, "Kelcy Smith" <notifications@github.com> wrote:
>
> > What are we defining as a 'domain' level object?
> >
> > On Thu, Mar 3, 2016 at 8:13 AM, David V. Hill <notifications@github.com>
> > wrote:
> >
> > > Those really aren't domain objects.
> > > On Mar 3, 2016 8:09 AM, "Clay Austin" <notifications@github.com>
> wrote:
> > >
> > > > this commit moves a few modules into the domain dir, and updates
> > pointers
> > > > to the moved modules
> > > > @klsmith-usgs <https://github.com/klsmith-usgs>
> > > > ------------------------------

> > > > You can view, comment on, or merge this pull request online at:
> > > >
> > > > https://github.com/USGS-EROS/espa-api/pull/9
> > > > Commit Summary
> > > >
> > > > - move dbconnect emails errors lpdaac lta nlaps user utils others

> into
> > > > domain dir
> > > >
> > > > File Changes
> > > >
>
> > > > - *M* api/api_logging.py
> > > > <https://github.com/USGS-EROS/espa-api/pull/9/files#diff-0> (2)
> > > > - *M* api/domain/config.py
> > > > <https://github.com/USGS-EROS/espa-api/pull/9/files#diff-1> (4)
> > > > - *R* api/domain/dbconnect.py
> > > > <https://github.com/USGS-EROS/espa-api/pull/9/files#diff-2> (0)
> > > > - *R* api/domain/emails.py
> > > > <https://github.com/USGS-EROS/espa-api/pull/9/files#diff-3> (0)
> > > > - *R* api/domain/errors.py
> > > > <https://github.com/USGS-EROS/espa-api/pull/9/files#diff-4> (0)
> > > > - *R* api/domain/lpdaac.py
> > > > <https://github.com/USGS-EROS/espa-api/pull/9/files#diff-5> (2)
> > > > - *R* api/domain/lta.py
> > > > <https://github.com/USGS-EROS/espa-api/pull/9/files#diff-6> (0)
> > > > - *M* api/domain/mock_order.py
> > > > <https://github.com/USGS-EROS/espa-api/pull/9/files#diff-7> (4)
> > > > - *R* api/domain/nlaps.py
> > > > <https://github.com/USGS-EROS/espa-api/pull/9/files#diff-8> (0)
> > > > - *R* api/domain/onlinecache.py
> > > > <https://github.com/USGS-EROS/espa-api/pull/9/files#diff-9> (2)
> > > > - *M* api/domain/order.py
> > > > <https://github.com/USGS-EROS/espa-api/pull/9/files#diff-10> (4)
> > > > - *M* api/domain/scene.py
> > > > <https://github.com/USGS-EROS/espa-api/pull/9/files#diff-11> (4)
> > > > - *M* api/domain/sensor.py
> > > > <https://github.com/USGS-EROS/espa-api/pull/9/files#diff-12> (5)
> > > > - *R* api/domain/sshcmd.py
> > > > <https://github.com/USGS-EROS/espa-api/pull/9/files#diff-13> (0)
> > > > - *R* api/domain/user.py
> > > > <https://github.com/USGS-EROS/espa-api/pull/9/files#diff-14> (6)
> > > > - *R* api/domain/utils.py
> > > > <https://github.com/USGS-EROS/espa-api/pull/9/files#diff-15> (2)
> > > > - *M* api/providers/ordering/ordering_provider.py
> > > > <https://github.com/USGS-EROS/espa-api/pull/9/files#diff-16> (10)
> > > > - *M* api/providers/ordering/production_provider.py
> > > > <https://github.com/USGS-EROS/espa-api/pull/9/files#diff-17> (16)
> > > > - *M* test/test_apiv0.py
> > > > <https://github.com/USGS-EROS/espa-api/pull/9/files#diff-18> (4)
> > > > - *A* test/test_flask_production_transportv0.py
> > > > <https://github.com/USGS-EROS/espa-api/pull/9/files#diff-19> (77)
> > > > - *M* test/test_flask_transportv0.py
> > > > <https://github.com/USGS-EROS/espa-api/pull/9/files#diff-20> (4)
> > > > - *M* test/test_production_apiv0.py
> > > > <https://github.com/USGS-EROS/espa-api/pull/9/files#diff-21> (4)
> > > > - *M* transport.py
> > > > <https://github.com/USGS-EROS/espa-api/pull/9/files#diff-22> (4)
> > > >
> > > > Patch Links:
> > > >
> > > > - https://github.com/USGS-EROS/espa-api/pull/9.patch
> > > > - https://github.com/USGS-EROS/espa-api/pull/9.diff

> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <https://github.com/USGS-EROS/espa-api/pull/9>.
> > >
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/USGS-EROS/espa-api/pull/9#issuecomment-191779103>.
> > >
> >
> >
> >
> > --
> > Kelcy Smith
> > Software Engineer
> > Stinger Ghaffarian Technologies (SGT, Inc.)
> > Contractor to the U.S. Geological Survey (USGS)
> > Earth Resources Observation and Science (EROS) Center
> > 47914 252nd St
> > Sioux Falls, South Dakota 57198
> > Office: (605) 594-2836
> > Fax: (605) 594-6529
> > Email: klsmith@usgs.gov
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/USGS-EROS/espa-api/pull/9#issuecomment-191780124>.

>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/USGS-EROS/espa-api/pull/9#issuecomment-191781458>.

>



-- 
Kelcy Smith
Software Engineer
Stinger Ghaffarian Technologies (SGT, Inc.)
Contractor to the U.S. Geological Survey (USGS)
Earth Resources Observation and Science (EROS) Center
47914 252nd St
Sioux Falls, South Dakota 57198
Office: (605) 594-2836
Fax: (605) 594-6529
Email: klsmith@usgs.gov

—

Reply to this email directly or view it on GitHub
<https://github.com/USGS-EROS/espa-api/pull/9#issuecomment-191786527>.

**Pull request closed without merging**
